/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.test.randomuser.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseName
 */

public class ResponseName {
  @JsonProperty("last")
  private String last = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("first")
  private String first = null;

  public ResponseName last(String last) {
    this.last = last;
    return this;
  }

   /**
   * Get last
   * @return last
  **/
  public String getLast() {
    return last;
  }

  public void setLast(String last) {
    this.last = last;
  }

  public ResponseName title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ResponseName first(String first) {
    this.first = first;
    return this;
  }

   /**
   * Get first
   * @return first
  **/
  public String getFirst() {
    return first;
  }

  public void setFirst(String first) {
    this.first = first;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseName Response_name = (ResponseName) o;
    return Objects.equals(this.last, Response_name.last) &&
        Objects.equals(this.title, Response_name.title) &&
        Objects.equals(this.first, Response_name.first);
  }

  @Override
  public int hashCode() {
    return Objects.hash(last, title, first);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseName {\n");
    
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
