/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.test.randomuser.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.test.randomuser.model.ResponseCoordinates;
import com.wavemaker.test.randomuser.model.ResponseStreet;
import com.wavemaker.test.randomuser.model.ResponseTimezone;
/**
 * ResponseLocation
 */

public class ResponseLocation {
  @JsonProperty("country")
  private String country = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("street")
  private ResponseStreet street = null;

  @JsonProperty("timezone")
  private ResponseTimezone timezone = null;

  @JsonProperty("postcode")
  private Integer postcode = null;

  @JsonProperty("coordinates")
  private ResponseCoordinates coordinates = null;

  @JsonProperty("state")
  private String state = null;

  public ResponseLocation country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public ResponseLocation city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ResponseLocation street(ResponseStreet street) {
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/
  public ResponseStreet getStreet() {
    return street;
  }

  public void setStreet(ResponseStreet street) {
    this.street = street;
  }

  public ResponseLocation timezone(ResponseTimezone timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  public ResponseTimezone getTimezone() {
    return timezone;
  }

  public void setTimezone(ResponseTimezone timezone) {
    this.timezone = timezone;
  }

  public ResponseLocation postcode(Integer postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  public Integer getPostcode() {
    return postcode;
  }

  public void setPostcode(Integer postcode) {
    this.postcode = postcode;
  }

  public ResponseLocation coordinates(ResponseCoordinates coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  public ResponseCoordinates getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(ResponseCoordinates coordinates) {
    this.coordinates = coordinates;
  }

  public ResponseLocation state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseLocation Response_location = (ResponseLocation) o;
    return Objects.equals(this.country, Response_location.country) &&
        Objects.equals(this.city, Response_location.city) &&
        Objects.equals(this.street, Response_location.street) &&
        Objects.equals(this.timezone, Response_location.timezone) &&
        Objects.equals(this.postcode, Response_location.postcode) &&
        Objects.equals(this.coordinates, Response_location.coordinates) &&
        Objects.equals(this.state, Response_location.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, city, street, timezone, postcode, coordinates, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseLocation {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
