/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.test.randomuser.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.test.randomuser.model.ResponseDob;
import com.wavemaker.test.randomuser.model.ResponseId;
import com.wavemaker.test.randomuser.model.ResponseLocation;
import com.wavemaker.test.randomuser.model.ResponseLogin;
import com.wavemaker.test.randomuser.model.ResponseName;
import com.wavemaker.test.randomuser.model.ResponsePicture;
import com.wavemaker.test.randomuser.model.ResponseRegistered;
/**
 * ResponseResultsEntryItem
 */

public class ResponseResultsEntryItem {
  @JsonProperty("nat")
  private String nat = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("dob")
  private ResponseDob dob = null;

  @JsonProperty("name")
  private ResponseName name = null;

  @JsonProperty("registered")
  private ResponseRegistered registered = null;

  @JsonProperty("location")
  private ResponseLocation location = null;

  @JsonProperty("id")
  private ResponseId id = null;

  @JsonProperty("login")
  private ResponseLogin login = null;

  @JsonProperty("cell")
  private String cell = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("picture")
  private ResponsePicture picture = null;

  public ResponseResultsEntryItem nat(String nat) {
    this.nat = nat;
    return this;
  }

   /**
   * Get nat
   * @return nat
  **/
  public String getNat() {
    return nat;
  }

  public void setNat(String nat) {
    this.nat = nat;
  }

  public ResponseResultsEntryItem gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public ResponseResultsEntryItem phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public ResponseResultsEntryItem dob(ResponseDob dob) {
    this.dob = dob;
    return this;
  }

   /**
   * Get dob
   * @return dob
  **/
  public ResponseDob getDob() {
    return dob;
  }

  public void setDob(ResponseDob dob) {
    this.dob = dob;
  }

  public ResponseResultsEntryItem name(ResponseName name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public ResponseName getName() {
    return name;
  }

  public void setName(ResponseName name) {
    this.name = name;
  }

  public ResponseResultsEntryItem registered(ResponseRegistered registered) {
    this.registered = registered;
    return this;
  }

   /**
   * Get registered
   * @return registered
  **/
  public ResponseRegistered getRegistered() {
    return registered;
  }

  public void setRegistered(ResponseRegistered registered) {
    this.registered = registered;
  }

  public ResponseResultsEntryItem location(ResponseLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  public ResponseLocation getLocation() {
    return location;
  }

  public void setLocation(ResponseLocation location) {
    this.location = location;
  }

  public ResponseResultsEntryItem id(ResponseId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public ResponseId getId() {
    return id;
  }

  public void setId(ResponseId id) {
    this.id = id;
  }

  public ResponseResultsEntryItem login(ResponseLogin login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  public ResponseLogin getLogin() {
    return login;
  }

  public void setLogin(ResponseLogin login) {
    this.login = login;
  }

  public ResponseResultsEntryItem cell(String cell) {
    this.cell = cell;
    return this;
  }

   /**
   * Get cell
   * @return cell
  **/
  public String getCell() {
    return cell;
  }

  public void setCell(String cell) {
    this.cell = cell;
  }

  public ResponseResultsEntryItem email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ResponseResultsEntryItem picture(ResponsePicture picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  public ResponsePicture getPicture() {
    return picture;
  }

  public void setPicture(ResponsePicture picture) {
    this.picture = picture;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseResultsEntryItem Response_resultsEntryItem = (ResponseResultsEntryItem) o;
    return Objects.equals(this.nat, Response_resultsEntryItem.nat) &&
        Objects.equals(this.gender, Response_resultsEntryItem.gender) &&
        Objects.equals(this.phone, Response_resultsEntryItem.phone) &&
        Objects.equals(this.dob, Response_resultsEntryItem.dob) &&
        Objects.equals(this.name, Response_resultsEntryItem.name) &&
        Objects.equals(this.registered, Response_resultsEntryItem.registered) &&
        Objects.equals(this.location, Response_resultsEntryItem.location) &&
        Objects.equals(this.id, Response_resultsEntryItem.id) &&
        Objects.equals(this.login, Response_resultsEntryItem.login) &&
        Objects.equals(this.cell, Response_resultsEntryItem.cell) &&
        Objects.equals(this.email, Response_resultsEntryItem.email) &&
        Objects.equals(this.picture, Response_resultsEntryItem.picture);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nat, gender, phone, dob, name, registered, location, id, login, cell, email, picture);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseResultsEntryItem {\n");
    
    sb.append("    nat: ").append(toIndentedString(nat)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    registered: ").append(toIndentedString(registered)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    cell: ").append(toIndentedString(cell)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
